### ISSUE TITLE
Extend Chakra-UI theme for the project.

### ISSUE THREAD

**Issue by PradhumnaPancholi** [BanklessDAO/liquity-frontend#2]
Setup custom theme for this project by extending Chakra-UI theme.

Note:- colors can be gathered from Figma designs.

Reference: - https://chakra-ui.com/docs/theming/customize-theme

**Comment by zberwaldt** [comment]
I can start here. I know you have a call in the works. I'll try to be available for it. My timezone is EST.

**Comment by PradhumnaPancholi** [comment]
Sounds Great! I am on EST as well. Do you already have Figma files?

**Comment by zberwaldt** [comment]
I do not have them yet. Are they on the discord channel?

**Comment by PradhumnaPancholi** [comment]
Yes

**Comment by PradhumnaPancholi** [comment]
Hey @zberwaldt, what's the status on this one... I see you have a few commits.

**Comment by zberwaldt** [comment]
@PradhumnaPancholi I have the folder scaffolded out, I have some basic overrides in place, also a few of the component overrides that are built from the Figma. Also some components that I thought might be useful for building out the design.

Do you want me to make a pull request so the theme is in and start making tasks for individual theme pieces?

**Comment by PradhumnaPancholi** [comment]
Yeah, sure... that would be awesome. I read your commit messages, it's really awesome of you to get that component overrides for us. I just wanna merge the theme so pages and components can use it.

**Comment by zberwaldt** [comment]
Sure, I'll keep plugging away at making more. If I can, I'll go create tasks for the project board too for any other contributors.

**Comment by PradhumnaPancholi** [comment]
What's your discord handle, again?

**Comment by zberwaldt** [comment]
@PradhumnaPancholi zberwaldt. My nickame is currently: zebrah?

**Comment by PradhumnaPancholi** [comment]
got it, thanks
